CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    phone VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS phones (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    phone VARCHAR(12) NOT NULL,
    is_fax BOOLEAN NOT NULL DEFAULT FALSE,
    description VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
    UNIQUE (phone)
    CHECK( length(phone) <= 12 )
);